<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RootNamespace>HVO.RoofControllerV4.Simulation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HVO.Iot.Devices" />
    <ProjectReference Include="../HVO.RoofControllerV4.Common/HVO.RoofControllerV4.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HVO.RoofControllerV4.RPi.Tests" />
  </ItemGroup>

</Project>
