<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup Label="Language and Framework Defaults">
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Label="Suppressed Warnings">
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <NoWarn>$(NoWarn);CS1030</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Build Output">
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Label="Code Quality">
    <Deterministic>true</Deterministic>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Label="Performance">
    <PublishReadyToRun Condition="'$(Configuration)' == 'Release'">true</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Release' and '$(IsPublishable)' == 'true'">false</PublishTrimmed>
  </PropertyGroup>
</Project>
